#PBS -N simulated_annealing
#PBS -q inferno
#PBS -A GT-jmcdaniel43-chemx
#PBS -o energies.$PBS_JOBID
#PBS -e error.$PBS_JOBID
#PBS -l nodes=1:ppn=1:gpus=1,mem=40gb
#PBS -l walltime=72:00:00

cd $PBS_O_WORKDIR

hostname

module load cuda/10.0
module load anaconda3

# fill this in with your OpenMM conda environment
source activate OpenMM

#export OPENMM_CUDA_COMPILER=$(which nvcc)

python simulated_annealing.py example_monolayer.pdb  &>> simulated_annealing.out
